// views/docs.js — the command reference (Design 8.2, 10.5).
//
// There is exactly one source of truth for command documentation: the
// generated `client-commands` registry the CLI embeds. This view renders that
// file and nothing else — no second copy of the docs lives in the app, so the
// app can never drift from the binary.
//
// The registry is generated by the engine's build, so a desktop-only checkout
// legitimately does not have one yet; that case gets a real explanation rather
// than an empty list.

import { el, icon, plural } from "./dom.js";

// Relative to the frontend root (`desktop/src/`), so this climbs out of `src/`
// and out of `desktop/` to reach the repository's generated docs.
// TODO(packaging): read it from the bundled resource directory through a host
// command instead — a packaged app cannot reach outside its asset root, so
// this dev-time path is the only one that resolves today.
const REGISTRY_URL = "../../docs/client-commands.generated.json";

export function mountDocs(root, api) {
  let registry = null;
  let query = "";
  let cancelled = false;

  const searchInput = el("input", {
    class: "input",
    type: "search",
    placeholder: "Search commands…",
    "aria-label": "Search commands",
    on: {
      input: (event) => {
        query = event.target.value.trim().toLowerCase();
        renderBody();
      },
    },
  });

  const countLabel = el("span", { class: "field-hint" });
  const body = el("div", { class: "docs-layout" });

  root.append(
    el(
      "div",
      { class: "view-scroll" },
      el(
        "div",
        { class: "view-head" },
        el(
          "div",
          {},
          el("h1", { class: "view-title", text: "Docs" }),
          el("p", {
            class: "view-sub",
            text: "The same command registry the wsync CLI embeds, rendered here so the app and the binary can never disagree.",
          }),
        ),
      ),
      el(
        "div",
        { class: "toolbar" },
        el("div", { class: "search" }, el("span", { class: "search-icon" }, icon("search", 13)), searchInput),
        countLabel,
      ),
      body,
    ),
  );

  function matches(command) {
    if (!query) return true;
    return `${command.name} ${command.title ?? ""} ${command.description ?? ""} ${command.category ?? ""}`
      .toLowerCase()
      .includes(query);
  }

  function renderBody() {
    if (registry === null) {
      body.replaceChildren(el("div", { class: "stage-empty", text: "Loading command registry…" }));
      return;
    }
    if (registry === false) {
      countLabel.textContent = "";
      body.replaceChildren(
        el(
          "div",
          { class: "empty" },
          el("div", { class: "empty-icon" }, icon("book", 17)),
          el("div", { class: "empty-title", text: "No command registry found" }),
          el("p", {
            class: "empty-body",
            text: "docs/client-commands.generated.json has not been generated yet. It is produced from the CLI's command registry when the engine builds, and this view will fill in as soon as it exists.",
          }),
          el("code", { class: "code", text: REGISTRY_URL }),
        ),
      );
      return;
    }

    const commands = (registry.commands ?? []).filter(matches);
    countLabel.textContent = query
      ? `${plural(commands.length, "match", "matches")}`
      : `${plural(registry.commands?.length ?? 0, "command")}`;

    if (commands.length === 0) {
      body.replaceChildren(el("div", { class: "stage-empty", text: `Nothing matches "${query}".` }));
      return;
    }

    const groups = new Map();
    for (const command of commands) {
      const category = command.category ?? "Other";
      if (!groups.has(category)) groups.set(category, []);
      groups.get(category).push(command);
    }

    const nodes = [];
    for (const [category, entries] of groups) {
      nodes.push(el("div", { class: "docs-category", text: category }));
      for (const command of entries) nodes.push(commandCard(command));
    }
    body.replaceChildren(...nodes);
  }

  function commandCard(command) {
    return el(
      "article",
      { class: "docs-command" },
      el(
        "div",
        { class: "docs-command-head" },
        el("span", { class: "docs-command-name", text: command.name }),
        command.category ? el("span", { class: "chip chip-plain", text: command.category }) : null,
      ),
      el(
        "div",
        { class: "docs-command-body" },
        command.description ? el("p", { class: "docs-command-desc", text: command.description }) : null,
        command.usage ? el("code", { class: "code", text: command.usage }) : null,
        ...(command.examples ?? []).map((example) => el("code", { class: "code", text: example })),
        ...(command.notes ?? []).map((note) => el("p", { class: "field-hint", text: note })),
      ),
    );
  }

  async function load() {
    try {
      const response = await fetch(REGISTRY_URL, { cache: "no-cache" });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const parsed = await response.json();
      if (cancelled) return;
      registry = parsed && Array.isArray(parsed.commands) ? parsed : false;
    } catch {
      if (cancelled) return;
      registry = false;
    }
    renderBody();
    api.setStatus(
      registry === false
        ? "Command registry has not been generated yet."
        : `${plural(registry.commands.length, "command")} in the registry.`,
      registry === false ? "warn" : "",
    );
  }

  renderBody();
  void load();

  return () => {
    cancelled = true;
  };
}
